### ISSUE TITLE
Mod IP Post Identification

### ISSUE THREAD

**Issue by Barbara-Pitt** [towards-a-new-leftypol/leftypol_lainchan#19]
Mods cannot correctly identify the user IP of posts. Every single post shows 127.0.0.1 . This includes post history.

**Comment by Barbara-Pitt** [comment]
we need to investigate the cause of this

**Comment by nonmakina** [comment]
Could it be something related to IP tables?
Such as:
`-A POSTROUTING -o br0 -j MASQUERADE`
Source:
https://discuss.linuxcontainers.org/t/how-to-get-users-real-ip-in-lxc-container/7700/3

**Comment by nonmakina** [comment]
I found no similar rule.

**Comment by nonmakina** [comment]
My current theory right now is that it might be some nginx forwarding shenanigans. 
Maybe setting some rules to correct the IPs on nginx might do the trick.

**Comment by towards-a-new-leftypol** [comment]
https://discuss.linuxcontainers.org/t/how-to-get-real-client-ip-when-using-lxd-to-forward-port-80/2079

**Comment by towards-a-new-leftypol** [comment]
PHP is using $_SERVER['REMOTE_ADDR'] to get the ip. From what I gather this comes from the webserver (nginx), which currently isn't proxied by another nginx, however the container's networking was done by lxc, the linked issue above seems to be the same problem we're having.

Perhaps it's possible to use iptables directly instead of letting lxc set up networking, but to be honest that's a bitch to do correctly.
Perhaps it's possible to use another proxy like nginx - but then we'd have to move the ssl cert stuff out of the container
or a proxy using the proxy protocol which preserves the real origin address - but I have no experience with this proxy protocol.

So the easiest solution is to just use cloudflare and have nginx read the real ip from a header.

**Comment by nonmakina** [comment]
Makes sense. Not sure how LXD is set up. I guess we could always set up an nginx server on the host machine if necessary, and have that write the appropriate headers. But, going forward with cloudfare seems to be the correct choice at the moment.

**Comment by nonmakina** [comment]
Update: DNS changes are on the way. Next step would be to set the nginx stuff for cloudfare.

**Comment by towards-a-new-leftypol** [comment]
Done.
